// PANCASANDYA — daftar 36 anggota kelas (nama publik + slug untuk key Firebase)
export const MEMBERS = [
  { name: "Afandi", slug: "afandi" },
  { name: "Afrizal Adi Pratama", slug: "afrizal-adi-pratama" },
  { name: "Aisha Faridah Putri", slug: "aisha-faridah-putri" },
  { name: "Anindya Ayu Kirana", slug: "anindya-ayu-kirana" },
  { name: "Argi Prayata Hascar", slug: "argi-prayata-hascar" },
  { name: "Arinta Sinar Kasih Rammadhani", slug: "arinta-sinar-kasih-rammadhani" },
  { name: "Asha Syifa", slug: "asha-syifa" },
  { name: "Cesyia Anggellina Saputri", slug: "cesyia-anggellina-saputri" },
  { name: "Desta Rafli Herdiansyah", slug: "desta-rafli-herdiansyah" },
  { name: "Dhea Fazri Astuti", slug: "dhea-fazri-astuti" },
  { name: "Evrilya Cindra Nur Mayang", slug: "evrilya-cindra-nur-mayang" },
  { name: "Fatimah Nur Fitriani", slug: "fatimah-nur-fitriani" },
  { name: "Febriana Nur Safira", slug: "febriana-nur-safira" },
  { name: "Gagarin Ingga Frencesra", slug: "gagarin-ingga-frencesra" },
  { name: "Galuh Meida Sari", slug: "galuh-meida-sari" },
  { name: "Gamat Imam Rivai", slug: "gamat-imam-rivai" },
  { name: "Glenda Riskiansah", slug: "glenda-riskiansah" },
  { name: "Kariza Izza Maulidia", slug: "kariza-izza-maulidia" },
  { name: "Kayla Shafa Fiorenza", slug: "kayla-shafa-fiorenza" },
  { name: "Keisha Citra Kirana", slug: "keisha-citra-kirana" },
  { name: "Khoirunisa Salsabila", slug: "khoirunisa-salsabila" },
  { name: "Lailatus Istiana Putri Winanti", slug: "lailatus-istiana-putri-winanti" },
  { name: "Maulana Tsaqif Alhafidh", slug: "maulana-tsaqif-alhafidh" },
  { name: "Maulida Azzahra", slug: "maulida-azzahra" },
  { name: "Muhammad Fahri Fakhrullah", slug: "muhammad-fahri-fakhrullah" },
  { name: "Nachila Zukhrifatul Latifa", slug: "nachila-zukhrifatul-latifa" },
  { name: "Nadia Frita Kusuma", slug: "nadia-frita-kusuma" },
  { name: "Nanda Messi Pratama", slug: "nanda-messi-pratama" },
  { name: "Nasyita Hidayah", slug: "nasyita-hidayah" },
  { name: "Revalina Amdhani", slug: "revalina-amdhani" },
  { name: "Safa Permata Linggarjati", slug: "safa-permata-linggarjati" },
  { name: "Sakhi Putri Hapsari", slug: "sakhi-putri-hapsari" },
  { name: "Shabria Difa Ramadhani", slug: "shabria-difa-ramadhani" },
  { name: "Sherly Arista", slug: "sherly-arista" },
  { name: "Syaamil Dhiyaulhaq", slug: "syaamil-dhiyaulhaq" },
  { name: "Verliyana Zahrotusyita", slug: "verliyana-zahrotusyita" },
];
